export const SET_GEO_DATA = 'SET_GEO_DATA' 
export const SET_YEAR_FILTER = 'SET_YEAR_FILTER'

export const SET_FOCUSED_MAP_POINT = 'SET_FOCUSED_MAP_POINT'
export const SET_MAP_FOCUS = 'SET_MAP_FOCUS' 

export const SET_FOCUSED_INFO_CARD = 'SET_FOCUSED_INFO_CARD'